use_frameworks!

target 'ZestySwiftContentEndpointWrapper_Example' do
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Alamofire', '~> 4.7'
  pod 'ZestySwiftContentEndpointWrapper', :path => '../'

  target 'ZestySwiftContentEndpointWrapper_Tests' do
    inherit! :search_paths

    
  end
end
