platform :ios, '10.0'
use_frameworks!

target 'ZestyJSONAPI_Example' do
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Alamofire', '~> 4.7'
  pod 'ZestyJSONAPI', :path => '../'
  
  target 'ZestyJSONAPI_Tests' do
    inherit! :search_paths

    
  end
end
